services:
  react-app:
    build: .
    container_name: react-essentials
    ports:
      - "8080:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    command: yarn start
